<?php
namespace app\models;

use app\services\TelegramService;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "recept_control".
 *
 * @property int      $id
 * @property string   $name
 * @property string   $date
 * @property string   $weight
 * @property string   $material
 * @property string   $is_where
 * @property string   $comment
 * @property int      $created_at
 * @property int      $created_by
 * @property int|null $updated_by
 * @property int|null $updated_at
 */
class Posts extends \yii\db\ActiveRecord {

  public $image;
  public $image_name;
  public $is_new=false;
  /**
   * {@inheritdoc}
   */
  public static function tableName() {
    return 'posts';
  }

  public function behaviors() {
    return [
      TimestampBehavior::className(),
      BlameableBehavior::className(),
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function rules() {
    return [
      [['date', 'is_where', 'material', 'weight'], 'required'],
      [['date','image'], 'safe'],
      [['is_where', 'material', 'weight','comment'], 'string'],

    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels() {
    return [
      'id' => Yii::t('app', 'ID'),
      'date' => Yii::t('app', 'Date'),
      'material' => Yii::t('app', 'Material'),
      'weight' => Yii::t('app', 'Weight'),
      'is_where' => Yii::t('app', 'Is Where'),
      'comment' => Yii::t('app', 'Comment'),
      'created_at' => Yii::t('app', 'Created at'),
      'created_by' => Yii::t('app', 'Created by'),
      'updated_by' => Yii::t('app', 'Updated by'),
      'updated_at' => Yii::t('app', 'Updated at'),
    ];
  }


  /**
   * @return ActiveQuery
   */
  public function getCreatedBy() {
    return $this->hasOne(User::className(), ['id' => 'created_by']);
  }

  /**
   * @return ActiveQuery
   */
  public function getUpdatedBy() {
    return $this->hasOne(User::className(), ['id' => 'updated_by']);
  }

  public function getUpdatedAtFormatted() {
    return (!empty($this->updated_at)) ? date('d.m.Y H:i', $this->updated_at) : '';
  }

  public function getCreatedAtFormatted() {
    return (!empty($this->created_at)) ? date('d.m.Y H:i', $this->created_at) : '';
  }


  public function upload()
  {
    if ($this->validate(false)) {
      $this->image_name = $this->id.'_'.time().'.'.$this->image->extension;
      if (!file_exists(Yii::getAlias('@img').'/posts/')) {
        mkdir(Yii::getAlias('@img').'/posts/', 0777, true);
      }
      $this->image->saveAs(Yii::getAlias('@img').'/posts/' . $this->image_name);
      return true;
    } else {
      return false;
    }
  }

  public function getImages()
  {
    $post_images = PostImages::find()
      ->where([
        'post_id' => $this->id
              ])->all();
    return $post_images;
  }


  public function beforeSave($insert) {
    if ($this->isNewRecord)
      $this->is_new=true;
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }


  public function afterSave($insert, $changedAttributes) {
    if ($this->is_new)
      TelegramService::sendToGroup($this->attributes);
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }


  public function imagesCount()
  {
      return (int)PostImages::find()
        ->where([
          'post_id' => $this->id
                ])->count();
  }
}
